### ISSUE TITLE
You can't select new (same) files to upload second time

### ISSUE THREAD

**Issue by bjarnef** [ProfessorFarnsworth/HTML-5-File-Upload#22]
I can choose files the upload by clicking the "Select Files" button, even it returns this error in console:

```
Error: $apply already in progress
    at Error (native)
    at g (http://localhost:61220/umbraco/lib/angular/1.1.5/angular.min.js:87:165)
    at Object.e.$apply (http://localhost:61220/umbraco/lib/angular/1.1.5/angular.min.js:92:362)
    at HTMLDivElement.<anonymous> (http://localhost:61220/umbraco/lib/angular/1.1.5/angular-mobile.js:269:13)
    at HTMLDivElement.x.event.dispatch (http://localhost:61220/umbraco/lib/jquery/jquery-2.0.3.min.js:10:11778)
    at HTMLDivElement.y.handle (http://localhost:61220/umbraco/lib/jquery/jquery-2.0.3.min.js:10:7906)
    at Object.x.event.trigger (http://localhost:61220/umbraco/lib/jquery/jquery-2.0.3.min.js:10:10751)
    at HTMLInputElement.<anonymous> (http://localhost:61220/umbraco/lib/jquery/jquery-2.0.3.min.js:10:17513)
    at Function.x.extend.each (http://localhost:61220/umbraco/lib/jquery/jquery-2.0.3.min.js:4:5466)
    at x.fn.x.each (http://localhost:61220/umbraco/lib/jquery/jquery-2.0.3.min.js:4:1905)
```

after it has finished the process I can't choose to upload the same files or files - they have to be different or I should refresh the page. However it is possible to choose the same file(s) to upload again via drag & drop. Even you usually don't upload same image mulitple times, it should still be possible and in that case just name the copies like: "My Image" (first upload), "My Image (1)", "My Image (2)", "My Image 3" ... etc, which it also does with drag & drop upload.

![2015-02-11_00-44-14](https://cloud.githubusercontent.com/assets/2919859/6139017/46ca23de-b187-11e4-9b00-7b14bbdd3b9d.jpg)

**Comment by ProfessorFarnsworth** [comment]
Hi, that should be fixed.
